error: impl Debug and Error traits
This patch requires Request, Response, and Error parameters to impl the
Debug trait, which allows TenoriteError to impl Debug and Error. By
allowing this, TenoriteError can be used with `.unwrap`, `.expect`, and
error-propagation libraries like `anyhow`.